/**
 * @fileoverview Body animation controller — pose-modulated noise.
 *
 * Instead of trying to directly retarget arm positions from pose landmarks
 * (which fails due to bone-local coordinate system mismatches), this system
 * uses pose data to MODULATE the intensity of Perlin-noise idle animation.
 *
 * When the user gestures more (arms moving away from rest), the noise
 * amplitude increases proportionally → avatar appears to react to body
 * language while always staying in natural, safe poses.
 *
 * Three activity signals:
 *  1. jawOpen  → speech intensity (existing from v7)
 *  2. arm activity → how far each arm deviates from resting position
 *  3. torso lean  → spine bones follow body lean (Euler, clamped)
 *
 * This guarantees:
 *  - Arms NEVER clip through the body
 *  - Poses are always anatomically valid (generated by noise within safe ranges)
 *  - More user movement → more avatar movement (natural correlation)
 */

import * as THREE from 'three';

// ============================================================================
// Simple 1D Perlin-like noise
// ============================================================================
class Noise1D {
  constructor(seed = 1) {
    this._p = new Uint8Array(512);
    const perm = new Uint8Array(256);
    for (let i = 0; i < 256; i++) perm[i] = i;
    let s = seed;
    for (let i = 255; i > 0; i--) {
      s = (s * 16807) % 2147483647;
      const j = s % (i + 1);
      [perm[i], perm[j]] = [perm[j], perm[i]];
    }
    for (let i = 0; i < 512; i++) this._p[i] = perm[i & 255];
  }

  _fade(t) { return t * t * t * (t * (t * 6 - 15) + 10); }
  _lerp(a, b, t) { return a + t * (b - a); }
  _grad(hash, x) {
    const h = hash & 15;
    const g = 1 + (h & 7);
    return ((h & 8) ? -g : g) * x;
  }

  noise(x) {
    const X = Math.floor(x) & 255;
    x -= Math.floor(x);
    const u = this._fade(x);
    return this._lerp(
      this._grad(this._p[X], x),
      this._grad(this._p[X + 1], x - 1),
      u
    ) * 0.5;
  }

  fbm(x, octaves = 3) {
    let v = 0, amp = 0.5, freq = 1;
    for (let i = 0; i < octaves; i++) {
      v += amp * this.noise(x * freq);
      amp *= 0.5;
      freq *= 2;
    }
    return v;
  }
}

// ============================================================================
// Bone config — noise parameters per bone
// ============================================================================
const BONE_RULES = [
  // Spine — subtle sway
  {
    pattern: /^(mixamorig:?)?Spine$/i,
    config: {
      seed: 11, group: 'spine',
      freqX: 0.25, freqY: 0.20, freqZ: 0.30,
      ampX: 0.06, ampY: 0.08, ampZ: 0.05,
      speechBoost: 1.8, poseBoost: 1.5,
    },
  },
  {
    pattern: /^(mixamorig:?)?Spine1$/i,
    config: {
      seed: 12, group: 'spine',
      freqX: 0.28, freqY: 0.22, freqZ: 0.33,
      ampX: 0.08, ampY: 0.10, ampZ: 0.06,
      speechBoost: 1.8, poseBoost: 1.5,
    },
  },
  {
    pattern: /^(mixamorig:?)?Spine2$/i,
    config: {
      seed: 13, group: 'spine',
      freqX: 0.30, freqY: 0.25, freqZ: 0.35,
      ampX: 0.10, ampY: 0.12, ampZ: 0.08,
      speechBoost: 2.0, poseBoost: 1.8,
    },
  },
  // Shoulders
  {
    pattern: /^(mixamorig:?)?LeftShoulder$/i,
    config: {
      seed: 21, group: 'leftArm',
      freqX: 0.35, freqY: 0.30, freqZ: 0.40,
      ampX: 0.12, ampY: 0.08, ampZ: 0.10,
      speechBoost: 2.5, poseBoost: 2.0,
    },
  },
  {
    pattern: /^(mixamorig:?)?RightShoulder$/i,
    config: {
      seed: 22, group: 'rightArm',
      freqX: 0.33, freqY: 0.32, freqZ: 0.38,
      ampX: 0.12, ampY: 0.08, ampZ: 0.10,
      speechBoost: 2.5, poseBoost: 2.0,
    },
  },
  // Upper arms
  {
    pattern: /^(mixamorig:?)?LeftArm$/i,
    config: {
      seed: 31, group: 'leftArm',
      freqX: 0.40, freqY: 0.35, freqZ: 0.30,
      ampX: 0.18, ampY: 0.15, ampZ: 0.12,
      speechBoost: 3.0, poseBoost: 3.0,
    },
  },
  {
    pattern: /^(mixamorig:?)?RightArm$/i,
    config: {
      seed: 32, group: 'rightArm',
      freqX: 0.38, freqY: 0.37, freqZ: 0.32,
      ampX: 0.18, ampY: 0.15, ampZ: 0.12,
      speechBoost: 3.0, poseBoost: 3.0,
    },
  },
  // Forearms
  {
    pattern: /^(mixamorig:?)?LeftForeArm$/i,
    config: {
      seed: 41, group: 'leftArm',
      freqX: 0.45, freqY: 0.40, freqZ: 0.35,
      ampX: 0.12, ampY: 0.10, ampZ: 0.08,
      speechBoost: 2.5, poseBoost: 2.5,
    },
  },
  {
    pattern: /^(mixamorig:?)?RightForeArm$/i,
    config: {
      seed: 42, group: 'rightArm',
      freqX: 0.43, freqY: 0.42, freqZ: 0.37,
      ampX: 0.12, ampY: 0.10, ampZ: 0.08,
      speechBoost: 2.5, poseBoost: 2.5,
    },
  },
];

// MediaPipe Pose Landmark indices
const LM_LEFT_SHOULDER  = 11;
const LM_RIGHT_SHOULDER = 12;
const LM_LEFT_ELBOW     = 13;
const LM_RIGHT_ELBOW    = 14;
const LM_LEFT_WRIST     = 15;
const LM_RIGHT_WRIST    = 16;
const LM_LEFT_HIP       = 23;
const LM_RIGHT_HIP      = 24;

const MIN_VISIBILITY = 0.5;

// ============================================================================
// IdleGestureAnimator
// ============================================================================
export class IdleGestureAnimator {
  constructor() {
    /** @private */
    this._targets = [];
    /** @private */
    this._time = 0;

    this.enabled = true;
    /** @type {number} Global intensity multiplier (0..2) */
    this.intensity = 1.0;

    /** @private Smoothed speech intensity */
    this._speechEnv = 0;

    /** @private Smoothed pose activity per group (0..1) */
    this._poseActivity = {
      spine: 0,
      leftArm: 0,
      rightArm: 0,
    };

    /** @private Smoothed spine lean for direct spine tracking */
    this._spineLean = { pitch: 0, roll: 0 };

    /** @private Reusable temp objects */
    this._tmpQuat = new THREE.Quaternion();
    this._tmpEuler = new THREE.Euler();
    this._deltaQuat = new THREE.Quaternion();
  }

  /**
   * Scan the avatar's skeleton and register matching bones.
   * @param {THREE.Object3D} avatarRoot
   */
  registerAvatar(avatarRoot) {
    this._targets = [];
    if (!avatarRoot) return;

    avatarRoot.traverse((obj) => {
      if (!obj.isBone && obj.type !== 'Bone') return;

      for (const rule of BONE_RULES) {
        if (rule.pattern.test(obj.name)) {
          this._targets.push({
            bone: obj,
            canonName: obj.name.replace(/^(mixamorig:?)?/i, ''),
            baseQuat: obj.quaternion.clone(),
            noise: new Noise1D(rule.config.seed),
            config: rule.config,
          });
          break;
        }
      }
    });

    console.log(
      `[IdleGesture] Registered ${this._targets.length} bones:`,
      this._targets.map((t) => t.bone.name).join(', ')
    );

    if (this._targets.length === 0) {
      console.warn('[IdleGesture] No matching bones found.');
    }
  }

  /** Clear registration. */
  clear() {
    for (const t of this._targets) {
      t.bone.quaternion.copy(t.baseQuat);
    }
    this._targets = [];
    this._poseActivity = { spine: 0, leftArm: 0, rightArm: 0 };
    this._spineLean = { pitch: 0, roll: 0 };
  }

  // ==========================================================================
  // Mode 1: Pure noise (no pose data)
  // ==========================================================================

  /**
   * @param {number} dt - ms
   * @param {Object<string, number>} blendShapes
   */
  update(dt, blendShapes) {
    if (!this.enabled || this._targets.length === 0) {
      for (const t of this._targets) t.bone.quaternion.slerp(t.baseQuat, 0.2);
      return;
    }

    this._time += dt / 1000;
    this._updateSpeechEnvelope(blendShapes);

    // No pose → activity stays at 0 (baseline noise only)
    for (const t of this._targets) {
      this._applyNoiseToBone(t, 0);  // poseActivity = 0
    }
  }

  // ==========================================================================
  // Mode 2: Pose-modulated noise
  // ==========================================================================

  /**
   * @param {number} dt - ms
   * @param {Object<string, number>} blendShapes
   * @param {Array} worldLandmarks
   * @param {boolean} mirrored
   */
  updateWithPose(dt, blendShapes, worldLandmarks, mirrored) {
    if (!this.enabled || this._targets.length === 0) {
      for (const t of this._targets) t.bone.quaternion.slerp(t.baseQuat, 0.2);
      return;
    }

    this._time += dt / 1000;
    this._updateSpeechEnvelope(blendShapes);

    // Compute pose activity from landmarks
    this._updatePoseActivity(worldLandmarks, mirrored);

    // Apply noise modulated by pose activity
    for (const t of this._targets) {
      const group = t.config.group;

      if (group === 'spine') {
        // Spine: apply direct lean + noise
        this._applySpineWithLean(t);
      } else {
        // Arms: noise modulated by arm activity
        const activity = this._poseActivity[group] || 0;
        this._applyNoiseToBone(t, activity);
      }
    }
  }

  // ==========================================================================
  // Pose activity computation
  // ==========================================================================

  /**
   * Compute how much each body part is moving/deviating from rest.
   * Activity is 0..1 where 0 = arms at rest, 1 = arms raised/moving a lot.
   * @private
   */
  _updatePoseActivity(worldLandmarks, mirrored) {
    if (!worldLandmarks || worldLandmarks.length < 25) return;

    const xSign = mirrored ? 1 : -1;
    const toVec3 = (lm) => new THREE.Vector3(xSign * lm.x, -lm.y, -lm.z);

    // Landmark indices (avatar left/right)
    const liS = mirrored ? LM_RIGHT_SHOULDER : LM_LEFT_SHOULDER;
    const riS = mirrored ? LM_LEFT_SHOULDER  : LM_RIGHT_SHOULDER;
    const liE = mirrored ? LM_RIGHT_ELBOW    : LM_LEFT_ELBOW;
    const riE = mirrored ? LM_LEFT_ELBOW     : LM_RIGHT_ELBOW;
    const liW = mirrored ? LM_RIGHT_WRIST    : LM_LEFT_WRIST;
    const riW = mirrored ? LM_LEFT_WRIST     : LM_RIGHT_WRIST;
    const liH = mirrored ? LM_RIGHT_HIP      : LM_LEFT_HIP;
    const riH = mirrored ? LM_LEFT_HIP       : LM_RIGHT_HIP;

    const lShoulder = toVec3(worldLandmarks[liS]);
    const rShoulder = toVec3(worldLandmarks[riS]);
    const lElbow    = toVec3(worldLandmarks[liE]);
    const rElbow    = toVec3(worldLandmarks[riE]);
    const lWrist    = toVec3(worldLandmarks[liW]);
    const rWrist    = toVec3(worldLandmarks[riW]);
    const lHip      = toVec3(worldLandmarks[liH]);
    const rHip      = toVec3(worldLandmarks[riH]);

    // --- Arm activity ---
    // Measure how far the arm deviates from "hanging straight down".
    // dot(armDir, down) = -1 when arm hangs down, 0 when horizontal, +1 when up
    const down = new THREE.Vector3(0, -1, 0);

    const lArmDir = lElbow.clone().sub(lShoulder).normalize();
    const rArmDir = rElbow.clone().sub(rShoulder).normalize();

    // Wrist deviation adds extra activity (gesticulating hands)
    const lForeDir = lWrist.clone().sub(lElbow).normalize();
    const rForeDir = rWrist.clone().sub(rElbow).normalize();

    // Activity = how much the arm is NOT hanging down (0=hanging, 1=raised)
    const lArmDot = lArmDir.dot(down);   // -1 when hanging, higher when raised
    const rArmDot = rArmDir.dot(down);
    const lForeDot = lForeDir.dot(down);
    const rForeDot = rForeDir.dot(down);

    // Convert dot product to 0..1 activity score
    // dot=-1 → hanging → activity=0
    // dot=0  → horizontal → activity=0.5
    // dot=1  → straight up → activity=1
    const dotToActivity = (d) => Math.max(0, (d + 1) * 0.5);

    const rawLeftArm  = Math.max(dotToActivity(lArmDot), dotToActivity(lForeDot) * 0.5);
    const rawRightArm = Math.max(dotToActivity(rArmDot), dotToActivity(rForeDot) * 0.5);

    // --- Spine lean ---
    const midShoulder = lShoulder.clone().add(rShoulder).multiplyScalar(0.5);
    const midHip = lHip.clone().add(rHip).multiplyScalar(0.5);
    const spineDir = midShoulder.clone().sub(midHip).normalize();

    const rawSpinePitch = Math.atan2(-spineDir.z, spineDir.y);
    const rawSpineRoll  = Math.atan2(spineDir.x, spineDir.y);
    const rawSpineActivity = Math.min(1, (Math.abs(rawSpinePitch) + Math.abs(rawSpineRoll)) * 3);

    // --- Smooth all activities (slow follow for natural feel) ---
    const alpha = 0.06;
    this._poseActivity.leftArm  += (rawLeftArm  - this._poseActivity.leftArm)  * alpha;
    this._poseActivity.rightArm += (rawRightArm - this._poseActivity.rightArm) * alpha;
    this._poseActivity.spine    += (rawSpineActivity - this._poseActivity.spine) * alpha;

    // Smooth spine lean for direct application
    const leanAlpha = 0.05;
    this._spineLean.pitch += (rawSpinePitch - this._spineLean.pitch) * leanAlpha;
    this._spineLean.roll  += (rawSpineRoll  - this._spineLean.roll)  * leanAlpha;
  }

  // ==========================================================================
  // Bone application
  // ==========================================================================

  /**
   * Apply noise to a bone, modulated by pose activity and speech.
   * @private
   * @param {Object} target - bone target
   * @param {number} poseActivity - 0..1, how active this body part is
   */
  _applyNoiseToBone(target, poseActivity) {
    const cfg = target.config;

    // Base amplitude: idle breathing-like motion (always present)
    const idleAmp = 0.4;
    // Speech boost
    const speechAmp = this._speechEnv * cfg.speechBoost;
    // Pose boost: arm activity increases noise amplitude
    const poseAmp = poseActivity * (cfg.poseBoost || 0);

    const totalAmp = (idleAmp + speechAmp + poseAmp) * this.intensity;

    const nx = target.noise.fbm(this._time * cfg.freqX + 0, 3);
    const ny = target.noise.fbm(this._time * cfg.freqY + 100, 3);
    const nz = target.noise.fbm(this._time * cfg.freqZ + 200, 3);

    this._tmpEuler.set(
      nx * cfg.ampX * totalAmp,
      ny * cfg.ampY * totalAmp,
      nz * cfg.ampZ * totalAmp,
      'XYZ'
    );
    this._deltaQuat.setFromEuler(this._tmpEuler);
    this._tmpQuat.copy(target.baseQuat).multiply(this._deltaQuat);
    target.bone.quaternion.slerp(this._tmpQuat, 0.5);
  }

  /**
   * Apply spine bone rotation: direct lean from pose + noise.
   * The spine lean is the ONE thing we can safely track directly
   * because it's a simple pitch/roll relative to vertical.
   * @private
   */
  _applySpineWithLean(target) {
    const cfg = target.config;
    const name = target.canonName;

    // Distribute spine lean across 3 spine bones
    const weight = name === 'Spine' ? 0.20 : name === 'Spine1' ? 0.25 : 0.35;
    const maxLean = 0.15;  // ~8.5° max per bone

    const leanX = THREE.MathUtils.clamp(this._spineLean.pitch * weight, -maxLean, maxLean);
    const leanZ = THREE.MathUtils.clamp(this._spineLean.roll  * weight, -maxLean, maxLean);

    // Add noise on top (modulated by spine activity + speech)
    const idleAmp = 0.3;
    const speechAmp = this._speechEnv * cfg.speechBoost;
    const poseAmp = this._poseActivity.spine * (cfg.poseBoost || 0);
    const noiseAmp = (idleAmp + speechAmp + poseAmp) * this.intensity;

    const nx = target.noise.fbm(this._time * cfg.freqX + 0, 3);
    const ny = target.noise.fbm(this._time * cfg.freqY + 100, 3);
    const nz = target.noise.fbm(this._time * cfg.freqZ + 200, 3);

    this._tmpEuler.set(
      leanX + nx * cfg.ampX * noiseAmp,
      ny * cfg.ampY * noiseAmp,
      leanZ + nz * cfg.ampZ * noiseAmp,
      'XYZ'
    );
    this._deltaQuat.setFromEuler(this._tmpEuler);
    this._tmpQuat.copy(target.baseQuat).multiply(this._deltaQuat);
    target.bone.quaternion.slerp(this._tmpQuat, 0.5);
  }

  // ==========================================================================
  // Shared
  // ==========================================================================

  /** @private */
  _updateSpeechEnvelope(blendShapes) {
    const jawOpen = blendShapes?.jawOpen || 0;
    const rawSpeech = Math.max(0, (jawOpen - 0.04) / 0.35);
    const targetSpeech = Math.min(1, rawSpeech);
    const coef = targetSpeech > this._speechEnv ? 0.25 : 0.04;
    this._speechEnv += (targetSpeech - this._speechEnv) * coef;
  }
}
